# Generated by Django 5.2.11 on 2026-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news.publisher'),
        ),
    ]
